### ISSUE TITLE
Bypass failed

### ISSUE THREAD

**Issue by ziyuewu1105** [KBzzi/HoYoKBreaker#2]
![1](https://github.com/KBzzi/HoYoKBreaker/assets/73162707/4e70962a-9d8e-4d4f-9d85-d43d351cb12c)
After I selected the folder, an error occurred. My executable file is 'YuanShen.exe'.

**Comment by KBzzi** [comment]
I have a preliminary understanding of what is the reason, it may be a judgment error of the program, I think it may be fixed tonight and published

**Comment by KBzzi** [comment]
Fixed，maybe?
